max_width = 120
ideal_width = 100
leeway = 5
tab_spaces = 4
newline_style = "Unix"
fn_brace_style = "PreferSameLine"
fn_return_indent = "WithArgs"
fn_args_paren_newline = true
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_arg_indent = "Tabbed"
where_density = "Tall"
where_indent = "Tabbed"
where_layout = "Horizontal"
where_pred_indent = "Visual"
generics_indent = "Visual"
struct_trailing_comma = "Vertical"
struct_lit_trailing_comma = "Vertical"
struct_lit_style = "Block"
enum_trailing_comma = true
report_todo = "Always"
report_fixme = "Never"
reorder_imports = false
expr_indent_style = "Tabbed"
closure_indent_style = "Visual"
single_line_if_else = true
format_strings = true
density = "Compressed"
rewrite_if_else = false
